Validate uarch instruction set after build
cartesi/machine-emulator pull request #108
Opened 2023-07-18 13:47 UTC by mpernambuco

This branch adds a simple validation step to the microarchitecture Makefile.
It checks if all instructions in `uarch-ram.elf` belong to the supported instruction set.
The motivation is to make it easier to test other toolchains and be alerted if it generates unsupported instructions.

2023-07-19 15:44 UTC, diegonehab submitted a review, later dismissed

2023-07-20 14:33 UTC, edubart requested changes

2023-07-20 14:33 UTC, edubart commented on uarch/Makefile
> +	lhu|lui|lw|lwu|or|ori|sb|sd|sh|sll|slli|slliw|sllw|slt|slti|sltiu||sltu|sra|srai|sraiw|sraw|srl|srli|srliw|srlw|sub|$\
There is an extra `|` here in `sltiu||sltu`

2023-07-20 19:12 UTC, edubart approved these changes

2023-10-27 11:55 UTC, edubart commented
I think we can merge this @vfusco

2024-03-14 21:50 UTC, vfusco commented
wont need this anymore. See #195

2024-03-14 21:50 UTC, closed without merging