Remove ROM and write devicetree directly to new DTB memory range
cartesi/machine-emulator pull request #138
Opened 2023-10-03 14:45 UTC by diegonehab

This PR cherry-picks the changes from a different PR by @edubart.
The central idea is the elimination of the ROM we used to build the device tree.
This is now built directly by the emulator, into a new memory range we call DTB.
The new memory range appears right before RAM and, at 1MiB, will enable more complex initialization of the Cartesi Machine.

Depends on https://github.com/cartesi/grpc-interfaces/pull/23  and https://github.com/cartesi/machine-emulator-defines/pull/8.

2023-10-03 19:33 UTC, edubart submitted a review, later dismissed
I reviewed most files, code and tested, looks good for me, made two comments of possible enhancements (not mandatory though).

2023-10-03 19:33 UTC, edubart commented on src/tests/util.lua
> +local function merkle_hash(data, start, log2_size)
I think this function and also the `back_merkle_tree_meta` could be useful in the public Lua API, we could move it to a module in `cartesi` Lua library, the code will also become more isolated from these test utils.

2023-10-03 19:33 UTC, edubart commented on src/tests/util.lua
> +    if log2_size > WORD_LOG2_SIZE then
Checking if we are trying to compute merkle hash of a page of zeros can speed up this function by 7x factor here, and this speed up our tests. Ex:

```lua
local ZERO_PAGE = string.rep('\x00', PAGE_SIZE)
local function merkle_hash(data, start, log2_size)
    if log2_size == PAGE_LOG2_SIZE and data:sub(start + 1, start + (1 << log2_size)) == ZERO_PAGE then
        return zero_keccak_hash_table[PAGE_LOG2_SIZE]
    end
```

2023-10-04 15:21 UTC, edubart approved these changes

2023-10-05 21:46 UTC, vfusco requested changes

2023-10-06 13:04 UTC, edubart approved these changes

2023-10-06 13:40 UTC, merged