Feature/replace uarch mmio with ecall
cartesi/machine-emulator pull request #195
Opened 2024-03-09 21:05 UTC by mpernambuco

2024-03-12 22:01 UTC, edubart requested changes

2024-03-12 22:17 UTC, edubart requested changes

2024-03-12 22:17 UTC, edubart commented on src/uarch-step.cpp
> +    auto note = a.make_scoped_note("ebreak");
Got this error when compiling and testing in release mode:
```
uarch-step.cpp:981:10: warning: unused variable ‘note’ [-Wunused-variable]
```

2024-03-14 13:11 UTC, edubart approved these changes

2024-03-15 20:18 UTC, diegonehab approved these changes

2024-03-15 20:31 UTC, vfusco approved these changes

2024-03-15 20:40 UTC, edubart approved these changes

2024-03-16 01:34 UTC, merged