feat: add C API to translate virtual address
cartesi/machine-emulator pull request #220
Opened 2024-04-01 22:29 UTC by edubart

This PR adds these two new functions to the public C API:

1. `cm_translate_virtual_memory` - Translates a virtual memory address to its corresponding physical memory address
2. `cm_get_memory_ptr` - Gets a raw host pointer corresponding to a physical memory address range.

The use case of 1. is to debug address translation from outside, this function was exposed to Lua and JSONRPC.

The use case of 2. is to allow reading memory from host directly large chunks of contiguous physical memory skipping unwanted and expansive memory copy when using the low level C API, this function doesn't make sense in Lua or JSONRPC APIs and are omitted there.

2024-04-02 13:09 UTC, mpolitzer commented
I would be more explicit with the naming: `translate_guest_physical_to_host_ptr` (may be a bit overkill, but you get the idea).
Also this only makes sense when looking up within page boundaries, do you plan to use this with large pages?

2024-04-02 15:12 UTC, edubart commented
> Also this only makes sense when looking up within page boundaries, do you plan to use this with large pages?
I do plan to use this on personal projects, taking care to use the added methods carefully, always within page boundaries.

> `translate_guest_physical_to_host_ptr`
Yea, kinda overkill, @diegonehab do you have name suggestions?

2024-04-05 12:41 UTC, diegonehab requested changes
Can we change this to "translate_virtual_address"? You are not really translating the virtual memory, after all.

2024-04-11 14:32 UTC, diegonehab approved these changes

2024-04-12 01:05 UTC, merged