Feat/uarch riscv tests refactor
cartesi/machine-emulator pull request #270
Opened 2024-09-02 20:32 UTC by mpolitzer

TODO: CI

Refactor `uarch-riscv-tests.lua` to accept a `--jobs` option and run its tasks in parallel.

close #187

2024-09-03 09:00 UTC, mpernambuco requested changes
Looks good.
It seems we could do without jq for this.

2024-09-04 12:33 UTC, mpernambuco requested changes
Regression in catalog.json format

2024-09-04 12:33 UTC, mpernambuco commented on tests/lua/uarch-riscv-tests.lua
> -        local logFilename = make_json_log_file_name(ctx.test_name, "-steps")
This change dropped the `-steps` suffix in the `logFilename` field of `uarch-reset` and `send-cmio-response`.
Diff 
``` 
--- /tmp/old/catalog.json	2024-08-09 10:40:07.000000000 -0300
+++ /tmp/new/catalog.json	2024-09-04 08:53:12.209167315 -0300

-  {"logFilename": "uarch-reset-steps.json", "binaryFilename": "", "steps": 1, "proofs":true, "proofsFrequency":1, "initialRootHash": "85d625da70a4582fd2085c074fb8dc8538fdcb9caafa67f5ddd5272d74223d90", "finalRootHash": "5b50373e88c3c73ad12e6585b5501aec912dbc5c487760c55068bcdd47038c76"},
-  {"logFilename": "send-cmio-response-steps.json", "binaryFilename": "", "steps": 1, "proofs":true, "proofsFrequency":1, "initialRootHash": "6ea144ae08d02645b0412b2b76a56dc74fe59fd89031967dbb28615731b98f4d", "finalRootHash": "0314add8d77e819e6866f7f66e6d782915628fae569d333cdc76d8071a52ed96"}
+  {"logFilename": "uarch-reset", "binaryFilename": "", "steps": 1, "proofs":true, "proofsFrequency":1, "initialRootHash": "85d625da70a4582fd2085c074fb8dc8538fdcb9caafa67f5ddd5272d74223d90", "finalRootHash": "5b50373e88c3c73ad12e6585b5501aec912dbc5c487760c55068bcdd47038c76"},
+  {"logFilename": "send-cmio-response", "binaryFilename": "", "steps": 1, "proofs":true, "proofsFrequency":1, "initialRootHash": "6ea144ae08d02645b0412b2b76a56dc74fe59fd89031967dbb28615731b98f4d", "finalRootHash": "0314add8d77e819e6866f7f66e6d782915628fae569d333cdc76d8071a52ed96"}
 
 ```

2024-09-04 17:41 UTC, mpernambuco approved these changes

2024-09-04 17:47 UTC, edubart approved these changes

2024-09-04 17:57 UTC, merged