Add log level and SIGTTOU control to JSONRPC remote cartesi machine server
cartesi/machine-emulator pull request #80
Opened 2023-06-09 15:58 UTC by diegonehab

The JSONRPC remote cartesi machine server was missing log-level control.
This PR adds this control, both by means of an environment variable `REMOTE_CARTESI_MACHINE_LOG_LEVEL`, or with a command-line option `--log-level` (which takes precedence).
It also adds SIGTTOU handling.

2023-06-12 12:45 UTC, edubart requested changes
It works and I am using this, just need minor changes, see comments, lets try to merge soon.

2023-06-12 12:45 UTC, edubart commented on src/jsonrpc-remote-machine.cpp
> +            help(program_name);
Help is missing the new `--log-level` option.

2023-06-12 12:45 UTC, edubart commented on src/jsonrpc-remote-machine.cpp
>  int main(int argc, char *argv[]) {
Linter warning:
```
/home/runner/work/machine-emulator/machine-emulator/src/jsonrpc-remote-machine.cpp:1718:5: error: an exception may be thrown in function 'main' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
int main(int argc, char *argv[]) {
```

2023-06-14 16:33 UTC, edubart approved these changes

2023-06-14 16:37 UTC, vfusco approved these changes

2023-06-14 20:45 UTC, merged